[workspace]
members = [
    'colmeia-bins',
    'colmeia-hypercore',
    'colmeia-hyperdrive',
    'colmeia-hyperstack',
    'colmeia-hyperswarm-dht',
    'colmeia-hyperswarm-mdns',
    'colmeiad',
]
