[package]
name = 'colmeia'
version = '0.1.0'
authors = ['Bruno Tavares']
edition = '2018'

[workspace]
members = ['colmeia-mdns']

[dependencies]
futures = '0.3'

[dependencies.colmeia-mdns]
path = './colmeia-mdns'

[dependencies.async-std]
version = '1.4.0'
features = ['unstable']
