[package]
name = 'colmeia'
version = '0.1.0'
authors = ['Bruno Tavares']
edition = '2018'

[workspace]
members = [
    'colmeia-mdns',
    'colmeia-proto',
]

[dependencies]
futures = '0.3'
env_logger = '0.7.1'

[dependencies.colmeia-mdns]
path = './colmeia-mdns'

[dependencies.colmeia-proto]
path = './colmeia-proto'

[dependencies.async-std]
version = '1.4.0'
features = ['unstable']
