[package]
name = 'colmeia'
version = '0.1.0'
authors = ['Bruno Tavares <connect+github@bltavares.com>']
edition = '2018'

[workspace]
members = [
    'colmeia-dat-mdns',
    'colmeia-dat-proto',
    'colmeia-dat-core',
]

[dependencies]
futures = '0.3'
env_logger = '0.7.1'
async-trait = '*'
hex = '*'
hypercore = '0.10.0'
random-access-storage = '2.0.0'
failure = '0.1.6'
random-access-memory = '*'

[dependencies.colmeia-dat-mdns]
path = './colmeia-dat-mdns'

[dependencies.colmeia-dat-proto]
path = './colmeia-dat-proto'

[dependencies.async-std]
version = '1.4.0'
features = ['unstable']

[dependencies.colmeia-dat-core]
path = './colmeia-dat-core'
